apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: your-dockerhub-user/cloudbook-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "cloudbook.cbig0owqa8c2.ap-south-1.rds.amazonaws.com"
            - name: DB_USER
              value: "admin"
            - name: DB_PASS
              value: "Admin123"
            - name: DB_NAME
              value: "cloudbook"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
