apiVersion: v1
kind: Secret
metadata:
  name: rds-secret
type: Opaque
data:
  DB_HOST: Y2xvdWRib29rLmNiaWcwb3dxYThjMi5hcC1zb3V0aC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USER: YWRtaW4=
  DB_PASSWORD: QWRtaW4xMjM=
  DB_NAME: Y2xvdWRib29r
